import { Agent, Task, Project, CalendarEvent, MemoryEntry, Document, Workflow, ActivityItem, SystemStatus, FocusArea, PriorityItem, DecisionItem } from './types';

export const agents: Agent[] = [
  {
    id: 'chief-architect',
    name: 'Chief Architect',
    role: 'Jay',
    status: 'working',
    currentFocus: 'Strategic planning and system architecture decisions',
    lastActivity: '2 minutes ago',
    capabilities: [
      'System architecture design',
      'Strategic decision making',
      'Code review and approval',
      'Technical direction',
      'Final authority on design',
    ],
  },
  {
    id: 'edgepilot',
    name: 'EdgePilot',
    role: 'Chief of Staff',
    status: 'working',
    currentFocus: 'Coordinating team priorities and execution flow',
    lastActivity: '5 minutes ago',
    capabilities: [
      'Team coordination',
      'Priority management',
      'Workflow optimization',
      'Progress tracking',
      'Resource allocation',
    ],
  },
  {
    id: 'deepforge',
    name: 'DeepForge',
    role: 'Research',
    status: 'idle',
    currentFocus: 'Analyzing market trends for trading opportunities',
    lastActivity: '1 hour ago',
    capabilities: [
      'Market research',
      'Competitor analysis',
      'AI tools discovery',
      'Trading strategy research',
      'Trend identification',
    ],
  },
  {
    id: 'scriptforge',
    name: 'ScriptForge',
    role: 'Content',
    status: 'working',
    currentFocus: 'Drafting YouTube script for trading education series',
    lastActivity: '15 minutes ago',
    capabilities: [
      'Content creation',
      'Script writing',
      'Educational materials',
      'Blog posts',
      'Course outlines',
    ],
  },
  {
    id: 'growthforge',
    name: 'GrowthForge',
    role: 'Marketing',
    status: 'blocked',
    currentFocus: 'Waiting on landing page completion for campaign launch',
    lastActivity: '3 hours ago',
    capabilities: [
      'Marketing strategy',
      'Funnel design',
      'Offer creation',
      'Audience targeting',
      'Conversion optimization',
    ],
  },
  {
    id: 'buildforge',
    name: 'BuildForge',
    role: 'Development',
    status: 'working',
    currentFocus: 'Building Mission Control dashboard (Phase 2)',
    lastActivity: 'Just now',
    capabilities: [
      'Full-stack development',
      'API integrations',
      'Automation workflows',
      'MVP development',
      'Trading tools',
    ],
  },
  {
    id: 'signalforge',
    name: 'SignalForge',
    role: 'Social',
    status: 'offline',
    currentFocus: 'Scheduled to start social content calendar tomorrow',
    lastActivity: '8 hours ago',
    capabilities: [
      'Social media strategy',
      'Content calendars',
      'TikTok hooks',
      'YouTube optimization',
      'Viral content structures',
    ],
  },
  {
    id: 'haven',
    name: 'Haven',
    role: 'Personal Life',
    status: 'idle',
    currentFocus: 'Ready to assist with personal life organization',
    lastActivity: 'Just now',
    capabilities: [
      'Daily planning',
      'Weekly planning',
      'Personal organization',
      'Habit tracking',
      'Family coordination',
      'Scheduling',
      'Health routines',
      'Education progress tracking',
      'Retirement preparation',
      'Reminders and checklists',
      'Travel preparation',
      'Stress reduction through structure',
    ],
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design system architecture for trading bot',
    description: 'Create comprehensive architecture diagram and component breakdown for the automated trading system.',
    assignedAgent: 'Chief Architect',
    priority: 'Critical',
    dueDate: '2026-03-25',
    project: 'Trading Systems',
    status: 'In Progress',
    activityLog: [
      { id: 'a1', timestamp: '2026-03-20T10:00:00Z', action: 'Task created', agent: 'EdgePilot' },
      { id: 'a2', timestamp: '2026-03-20T14:30:00Z', action: 'Started working on architecture', agent: 'Chief Architect' },
    ],
  },
  {
    id: 'task-2',
    title: 'Research prop firm evaluation criteria',
    description: 'Analyze top 5 prop firms and document their evaluation rules, payout structures, and restrictions.',
    assignedAgent: 'DeepForge',
    priority: 'High',
    dueDate: '2026-03-24',
    project: 'Trading Systems',
    status: 'In Progress',
    activityLog: [
      { id: 'a3', timestamp: '2026-03-19T09:00:00Z', action: 'Task assigned', agent: 'EdgePilot' },
      { id: 'a4', timestamp: '2026-03-20T11:00:00Z', action: 'Completed firm comparison spreadsheet', agent: 'DeepForge' },
    ],
  },
  {
    id: 'task-3',
    title: 'Write "Trade Truths Unfiltered" Episode 1 script',
    description: 'Create engaging script covering risk management basics for beginner traders.',
    assignedAgent: 'ScriptForge',
    priority: 'High',
    dueDate: '2026-03-23',
    project: 'Content Engine',
    status: 'In Progress',
    activityLog: [
      { id: 'a5', timestamp: '2026-03-20T08:00:00Z', action: 'Started draft', agent: 'ScriptForge' },
      { id: 'a6', timestamp: '2026-03-20T15:00:00Z', action: 'First draft completed', agent: 'ScriptForge' },
    ],
  },
  {
    id: 'task-4',
    title: 'Build Mission Control Dashboard',
    description: 'Create the central command center for managing agents, tasks, and priorities.',
    assignedAgent: 'BuildForge',
    priority: 'Critical',
    dueDate: '2026-03-21',
    project: 'Automation Systems',
    status: 'In Progress',
    activityLog: [
      { id: 'a7', timestamp: '2026-03-21T04:00:00Z', action: 'Phase 1 started', agent: 'EdgePilot' },
      { id: 'a8', timestamp: '2026-03-21T12:00:00Z', action: 'Kanban board implemented', agent: 'BuildForge' },
    ],
  },
  {
    id: 'task-5',
    title: 'Design landing page for trading course',
    description: 'Create high-converting landing page mockup with clear value proposition and CTA.',
    assignedAgent: 'GrowthForge',
    priority: 'Medium',
    dueDate: '2026-03-26',
    project: 'SaaS MVPs',
    status: 'Backlog',
    activityLog: [
      { id: 'a9', timestamp: '2026-03-18T10:00:00Z', action: 'Task created', agent: 'EdgePilot' },
    ],
  },
  {
    id: 'task-6',
    title: 'Create social media content calendar',
    description: 'Plan 30 days of content across TikTok, Twitter, and YouTube Shorts.',
    assignedAgent: 'SignalForge',
    priority: 'Medium',
    dueDate: '2026-03-28',
    project: 'Content Engine',
    status: 'Backlog',
    activityLog: [
      { id: 'a10', timestamp: '2026-03-19T14:00:00Z', action: 'Task assigned', agent: 'EdgePilot' },
    ],
  },
  {
    id: 'task-7',
    title: 'Implement Pine Script strategy backtester',
    description: 'Build tool to backtest TradingView strategies with historical data.',
    assignedAgent: 'BuildForge',
    priority: 'High',
    dueDate: '2026-03-30',
    project: 'Trading Systems',
    status: 'Backlog',
    activityLog: [
      { id: 'a11', timestamp: '2026-03-19T16:00:00Z', action: 'Requirements gathered', agent: 'DeepForge' },
    ],
  },
  {
    id: 'task-8',
    title: 'Review and approve content strategy',
    description: 'Review the quarterly content plan and provide feedback.',
    assignedAgent: 'Chief Architect',
    priority: 'Medium',
    dueDate: '2026-03-22',
    project: 'Content Engine',
    status: 'Review',
    activityLog: [
      { id: 'a12', timestamp: '2026-03-20T09:00:00Z', action: 'Submitted for review', agent: 'ScriptForge' },
      { id: 'a13', timestamp: '2026-03-20T10:00:00Z', action: 'Review requested', agent: 'EdgePilot' },
    ],
  },
  {
    id: 'task-9',
    title: 'Set up automated email sequences',
    description: 'Configure welcome series and nurture sequences in email platform.',
    assignedAgent: 'GrowthForge',
    priority: 'Low',
    dueDate: '2026-04-01',
    project: 'SaaS MVPs',
    status: 'Backlog',
    activityLog: [
      { id: 'a14', timestamp: '2026-03-17T11:00:00Z', action: 'Task created', agent: 'EdgePilot' },
    ],
  },
  {
    id: 'task-10',
    title: 'Document API integration patterns',
    description: 'Create documentation for standard API integration approaches used across projects.',
    assignedAgent: 'BuildForge',
    priority: 'Low',
    dueDate: '2026-03-29',
    project: 'AI Tools',
    status: 'Done',
    activityLog: [
      { id: 'a15', timestamp: '2026-03-15T09:00:00Z', action: 'Task started', agent: 'BuildForge' },
      { id: 'a16', timestamp: '2026-03-18T17:00:00Z', action: 'Documentation completed', agent: 'BuildForge' },
      { id: 'a17', timestamp: '2026-03-19T10:00:00Z', action: 'Marked as done', agent: 'EdgePilot' },
    ],
  },
  {
    id: 'task-11',
    title: 'Research competitor YouTube channels',
    description: 'Analyze top 10 trading education channels for content gaps and opportunities.',
    assignedAgent: 'DeepForge',
    priority: 'Medium',
    dueDate: '2026-03-24',
    project: 'Content Engine',
    status: 'Done',
    activityLog: [
      { id: 'a18', timestamp: '2026-03-16T08:00:00Z', action: 'Research started', agent: 'DeepForge' },
      { id: 'a19', timestamp: '2026-03-18T14:00:00Z', action: 'Analysis complete', agent: 'DeepForge' },
    ],
  },
  {
    id: 'task-12',
    title: 'Fix responsive layout issues',
    description: 'Address mobile layout problems on the main dashboard.',
    assignedAgent: 'BuildForge',
    priority: 'High',
    dueDate: '2026-03-20',
    project: 'Automation Systems',
    status: 'Review',
    activityLog: [
      { id: 'a20', timestamp: '2026-03-19T13:00:00Z', action: 'Bug reported', agent: 'EdgePilot' },
      { id: 'a21', timestamp: '2026-03-20T10:00:00Z', action: 'Fix implemented', agent: 'BuildForge' },
      { id: 'a22', timestamp: '2026-03-20T11:00:00Z', action: 'Ready for review', agent: 'BuildForge' },
    ],
  },
];

export const projectsData: Project[] = [
  {
    id: 'proj-1',
    name: 'Trading Systems',
    description: 'Automated trading infrastructure including backtesting, execution engines, and risk management systems for prop firm evaluations.',
    progress: 35,
    status: 'Active',
    linkedTaskCount: 4,
    linkedDocumentCount: 3,
    milestones: [
      { id: 'm1', title: 'Architecture Design', completed: true, dueDate: '2026-03-15' },
      { id: 'm2', title: 'Backtester MVP', completed: true, dueDate: '2026-03-20' },
      { id: 'm3', title: 'Execution Engine', completed: false, dueDate: '2026-04-05' },
      { id: 'm4', title: 'Risk Manager', completed: false, dueDate: '2026-04-15' },
    ],
    lastUpdated: '2026-03-21T10:30:00Z',
    createdAt: '2026-03-01T00:00:00Z',
    category: 'Trading',
  },
  {
    id: 'proj-2',
    name: 'AI Tools',
    description: 'Internal AI-powered tools for automation, content generation, and workflow enhancement across all projects.',
    progress: 60,
    status: 'Active',
    linkedTaskCount: 3,
    linkedDocumentCount: 5,
    milestones: [
      { id: 'm5', title: 'API Integration Patterns', completed: true, dueDate: '2026-03-10' },
      { id: 'm6', title: 'Agent Framework', completed: true, dueDate: '2026-03-18' },
      { id: 'm7', title: 'Content Generator', completed: false, dueDate: '2026-03-30' },
      { id: 'm8', title: 'Workflow Automation', completed: false, dueDate: '2026-04-10' },
    ],
    lastUpdated: '2026-03-20T16:45:00Z',
    createdAt: '2026-02-15T00:00:00Z',
    category: 'Development',
  },
  {
    id: 'proj-3',
    name: 'Automation Systems',
    description: 'Mission Control dashboard and supporting infrastructure for managing agents, tasks, and operational workflows.',
    progress: 75,
    status: 'Active',
    linkedTaskCount: 5,
    linkedDocumentCount: 4,
    milestones: [
      { id: 'm9', title: 'Phase 1: Core Layout', completed: true, dueDate: '2026-03-15' },
      { id: 'm10', title: 'Phase 2: Projects & Calendar', completed: false, dueDate: '2026-03-22' },
      { id: 'm11', title: 'Phase 3: Integrations', completed: false, dueDate: '2026-04-01' },
      { id: 'm12', title: 'Phase 4: Analytics', completed: false, dueDate: '2026-04-15' },
    ],
    lastUpdated: '2026-03-21T12:00:00Z',
    createdAt: '2026-03-10T00:00:00Z',
    category: 'Infrastructure',
  },
  {
    id: 'proj-4',
    name: 'Content Engine',
    description: 'Multi-platform content creation system including YouTube series, blog posts, social media, and educational courses.',
    progress: 45,
    status: 'Active',
    linkedTaskCount: 6,
    linkedDocumentCount: 8,
    milestones: [
      { id: 'm13', title: 'Channel Strategy', completed: true, dueDate: '2026-03-10' },
      { id: 'm14', title: 'Trade Truths Ep.1', completed: false, dueDate: '2026-03-23' },
      { id: 'm15', title: 'Content Calendar', completed: false, dueDate: '2026-03-28' },
      { id: 'm16', title: 'Course Outline', completed: false, dueDate: '2026-04-20' },
    ],
    lastUpdated: '2026-03-20T15:00:00Z',
    createdAt: '2026-02-20T00:00:00Z',
    category: 'Content',
  },
  {
    id: 'proj-5',
    name: 'SaaS MVPs',
    description: 'Rapid prototyping and validation of SaaS product ideas with landing pages, MVPs, and market testing.',
    progress: 15,
    status: 'Planning',
    linkedTaskCount: 2,
    linkedDocumentCount: 2,
    milestones: [
      { id: 'm17', title: 'Idea Validation', completed: true, dueDate: '2026-03-15' },
      { id: 'm18', title: 'Landing Page Design', completed: false, dueDate: '2026-03-26' },
      { id: 'm19', title: 'MVP Build', completed: false, dueDate: '2026-04-30' },
      { id: 'm20', title: 'Market Testing', completed: false, dueDate: '2026-05-15' },
    ],
    lastUpdated: '2026-03-18T11:00:00Z',
    createdAt: '2026-03-05T00:00:00Z',
    category: 'Business',
  },
];

// Generate calendar events for current month (March 2026)
const currentYear = 2026;
const currentMonth = 2; // March (0-indexed)

export const calendarEvents: CalendarEvent[] = [
  // Task due dates
  { id: 'cal-1', title: 'Task Due: Trading Bot Architecture', start: new Date(currentYear, currentMonth, 25, 9, 0), end: new Date(currentYear, currentMonth, 25, 10, 0), type: 'task', relatedTaskId: 'task-1' },
  { id: 'cal-2', title: 'Task Due: Prop Firm Research', start: new Date(currentYear, currentMonth, 24, 9, 0), end: new Date(currentYear, currentMonth, 24, 10, 0), type: 'task', relatedTaskId: 'task-2' },
  { id: 'cal-3', title: 'Task Due: Episode 1 Script', start: new Date(currentYear, currentMonth, 23, 9, 0), end: new Date(currentYear, currentMonth, 23, 10, 0), type: 'task', relatedTaskId: 'task-3' },
  { id: 'cal-4', title: 'Task Due: Content Strategy Review', start: new Date(currentYear, currentMonth, 22, 14, 0), end: new Date(currentYear, currentMonth, 22, 15, 0), type: 'task', relatedTaskId: 'task-8' },
  
  // Trading windows (daily 10:30-11:30 PM JST)
  { id: 'cal-t1', title: 'Trading Window', start: new Date(currentYear, currentMonth, 21, 22, 30), end: new Date(currentYear, currentMonth, 21, 23, 30), type: 'trading' },
  { id: 'cal-t2', title: 'Trading Window', start: new Date(currentYear, currentMonth, 22, 22, 30), end: new Date(currentYear, currentMonth, 22, 23, 30), type: 'trading' },
  { id: 'cal-t3', title: 'Trading Window', start: new Date(currentYear, currentMonth, 23, 22, 30), end: new Date(currentYear, currentMonth, 23, 23, 30), type: 'trading' },
  { id: 'cal-t4', title: 'Trading Window', start: new Date(currentYear, currentMonth, 24, 22, 30), end: new Date(currentYear, currentMonth, 24, 23, 30), type: 'trading' },
  { id: 'cal-t5', title: 'Trading Window', start: new Date(currentYear, currentMonth, 25, 22, 30), end: new Date(currentYear, currentMonth, 25, 23, 30), type: 'trading' },
  { id: 'cal-t6', title: 'Trading Window', start: new Date(currentYear, currentMonth, 26, 22, 30), end: new Date(currentYear, currentMonth, 26, 23, 30), type: 'trading' },
  { id: 'cal-t7', title: 'Trading Window', start: new Date(currentYear, currentMonth, 27, 22, 30), end: new Date(currentYear, currentMonth, 27, 23, 30), type: 'trading' },
  
  // Automation events
  { id: 'cal-a1', title: 'Daily Data Sync', start: new Date(currentYear, currentMonth, 21, 6, 0), end: new Date(currentYear, currentMonth, 21, 6, 30), type: 'automation' },
  { id: 'cal-a2', title: 'Daily Data Sync', start: new Date(currentYear, currentMonth, 22, 6, 0), end: new Date(currentYear, currentMonth, 22, 6, 30), type: 'automation' },
  { id: 'cal-a3', title: 'Weekly Report Generation', start: new Date(currentYear, currentMonth, 23, 7, 0), end: new Date(currentYear, currentMonth, 23, 7, 30), type: 'automation' },
  { id: 'cal-a4', title: 'Market Data Refresh', start: new Date(currentYear, currentMonth, 24, 8, 0), end: new Date(currentYear, currentMonth, 24, 8, 15), type: 'automation' },
  
  // Workflow schedules
  { id: 'cal-w1', title: 'Content Review Workflow', start: new Date(currentYear, currentMonth, 22, 10, 0), end: new Date(currentYear, currentMonth, 22, 11, 0), type: 'workflow' },
  { id: 'cal-w2', title: 'Agent Coordination Sync', start: new Date(currentYear, currentMonth, 24, 14, 0), end: new Date(currentYear, currentMonth, 24, 15, 0), type: 'workflow' },
  { id: 'cal-w3', title: 'Weekly Planning Session', start: new Date(currentYear, currentMonth, 23, 9, 0), end: new Date(currentYear, currentMonth, 23, 10, 30), type: 'workflow' },
  
  // Meetings
  { id: 'cal-m1', title: 'Team Standup', start: new Date(currentYear, currentMonth, 21, 9, 0), end: new Date(currentYear, currentMonth, 21, 9, 30), type: 'meeting' },
  { id: 'cal-m2', title: 'Architecture Review', start: new Date(currentYear, currentMonth, 25, 15, 0), end: new Date(currentYear, currentMonth, 25, 16, 0), type: 'meeting' },
  { id: 'cal-m3', title: 'Monthly Retrospective', start: new Date(currentYear, currentMonth, 28, 10, 0), end: new Date(currentYear, currentMonth, 28, 11, 0), type: 'meeting' },
];

export const memoryEntries: MemoryEntry[] = [
  {
    id: 'mem-1',
    title: 'Trading Strategy: Risk Management Principles',
    summary: 'Key principles for managing risk in automated trading systems including position sizing, stop losses, and drawdown limits.',
    content: 'Full content about risk management principles...',
    tags: ['Research', 'Strategy'],
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-03-18T10:00:00Z',
    relatedProjectId: 'proj-1',
  },
  {
    id: 'mem-2',
    title: 'Content Strategy: Trade Truths Format',
    summary: 'Format guidelines for the Trade Truths Unfiltered series including episode structure, length, and tone.',
    content: 'Full content about content strategy...',
    tags: ['Content', 'Strategy'],
    createdAt: '2026-03-15T14:30:00Z',
    updatedAt: '2026-03-16T09:00:00Z',
    relatedProjectId: 'proj-4',
  },
  {
    id: 'mem-3',
    title: 'Technical Decision: Agent Architecture',
    summary: 'Decision to use a modular agent architecture with standardized communication protocols.',
    content: 'Full content about agent architecture decision...',
    tags: ['Technical', 'Decisions'],
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
    relatedProjectId: 'proj-3',
  },
  {
    id: 'mem-4',
    title: 'Research: Top Prop Firms 2026',
    summary: 'Comparison of top 5 prop firms including evaluation criteria, payout structures, and restrictions.',
    content: 'Full content about prop firm research...',
    tags: ['Research', 'Strategy'],
    createdAt: '2026-03-12T16:00:00Z',
    updatedAt: '2026-03-14T10:00:00Z',
    relatedProjectId: 'proj-1',
  },
  {
    id: 'mem-5',
    title: 'AI Tool Discovery: Claude vs GPT-4',
    summary: 'Comparison of Claude and GPT-4 for content generation tasks with recommendations.',
    content: 'Full content about AI tool comparison...',
    tags: ['Research', 'Technical'],
    createdAt: '2026-03-08T13:00:00Z',
    updatedAt: '2026-03-08T13:00:00Z',
    relatedProjectId: 'proj-2',
  },
  {
    id: 'mem-6',
    title: 'SaaS MVP Validation Framework',
    summary: 'Framework for validating SaaS ideas quickly including landing page tests and pre-sales.',
    content: 'Full content about SaaS validation...',
    tags: ['Strategy', 'Content'],
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-03-06T15:00:00Z',
    relatedProjectId: 'proj-5',
  },
  {
    id: 'mem-7',
    title: 'Automation Workflow: Content Pipeline',
    summary: 'End-to-end workflow for content creation from ideation to publication.',
    content: 'Full content about content pipeline...',
    tags: ['Technical', 'Strategy'],
    createdAt: '2026-03-14T10:00:00Z',
    updatedAt: '2026-03-14T10:00:00Z',
    relatedProjectId: 'proj-3',
  },
  {
    id: 'mem-8',
    title: 'Decision: Trading Time Window',
    summary: 'Decision to trade during 10:30-11:30 PM JST window to align with US market hours.',
    content: 'Full content about trading window decision...',
    tags: ['Decisions', 'Strategy'],
    createdAt: '2026-03-01T20:00:00Z',
    updatedAt: '2026-03-01T20:00:00Z',
    relatedProjectId: 'proj-1',
  },
];

export const documents: Document[] = [
  {
    id: 'doc-1',
    title: 'Trading Systems Architecture',
    category: 'Technical',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-20T14:00:00Z',
    relatedProjectId: 'proj-1',
  },
  {
    id: 'doc-2',
    title: 'Q2 Content Strategy',
    category: 'Strategy',
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-03-15T11:00:00Z',
    relatedProjectId: 'proj-4',
  },
  {
    id: 'doc-3',
    title: 'Agent Communication Protocol',
    category: 'Technical',
    createdAt: '2026-03-12T13:00:00Z',
    updatedAt: '2026-03-12T13:00:00Z',
    relatedProjectId: 'proj-3',
  },
  {
    id: 'doc-4',
    title: 'Prop Firm Comparison Matrix',
    category: 'Research',
    createdAt: '2026-03-08T15:00:00Z',
    updatedAt: '2026-03-18T16:00:00Z',
    relatedProjectId: 'proj-1',
  },
  {
    id: 'doc-5',
    title: 'SaaS MVP Launch Checklist',
    category: 'Operations',
    createdAt: '2026-03-14T10:00:00Z',
    updatedAt: '2026-03-14T10:00:00Z',
    relatedProjectId: 'proj-5',
  },
  {
    id: 'doc-6',
    title: 'Trade Truths Episode Guide',
    category: 'Content',
    createdAt: '2026-03-16T11:00:00Z',
    updatedAt: '2026-03-19T09:00:00Z',
    relatedProjectId: 'proj-4',
  },
  {
    id: 'doc-7',
    title: 'API Integration Standards',
    category: 'Technical',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-18T17:00:00Z',
    relatedProjectId: 'proj-2',
  },
  {
    id: 'doc-8',
    title: 'Weekly Operations Report',
    category: 'Operations',
    createdAt: '2026-03-20T07:00:00Z',
    updatedAt: '2026-03-20T07:00:00Z',
    relatedProjectId: 'proj-3',
  },
  {
    id: 'doc-9',
    title: 'AI Tools Evaluation Report',
    category: 'Research',
    createdAt: '2026-03-07T14:00:00Z',
    updatedAt: '2026-03-08T13:00:00Z',
    relatedProjectId: 'proj-2',
  },
  {
    id: 'doc-10',
    title: 'Mission Control User Guide',
    category: 'Content',
    createdAt: '2026-03-19T10:00:00Z',
    updatedAt: '2026-03-21T12:00:00Z',
    relatedProjectId: 'proj-3',
  },
];

export const workflows: Workflow[] = [
  {
    id: 'wf-1',
    name: 'Content Review Pipeline',
    description: 'Automated workflow for reviewing and approving content before publication.',
    status: 'running',
    lastRun: '2026-03-21T08:00:00Z',
    nextRun: '2026-03-22T08:00:00Z',
    runCount: 45,
  },
  {
    id: 'wf-2',
    name: 'Daily Market Data Sync',
    description: 'Fetches and processes daily market data for trading analysis.',
    status: 'running',
    lastRun: '2026-03-21T06:00:00Z',
    nextRun: '2026-03-22T06:00:00Z',
    runCount: 128,
  },
  {
    id: 'wf-3',
    name: 'Agent Coordination Sync',
    description: 'Synchronizes task assignments and priorities across all agents.',
    status: 'running',
    lastRun: '2026-03-21T09:00:00Z',
    nextRun: '2026-03-21T15:00:00Z',
    runCount: 312,
  },
  {
    id: 'wf-4',
    name: 'Weekly Report Generator',
    description: 'Generates weekly performance and progress reports.',
    status: 'idle',
    lastRun: '2026-03-16T07:00:00Z',
    nextRun: '2026-03-23T07:00:00Z',
    runCount: 12,
  },
];

export const recentActivities: ActivityItem[] = [
  { id: 'act-1', timestamp: '2026-03-21T12:00:00Z', type: 'task', description: 'BuildForge completed Phase 1 of Mission Control dashboard', agent: 'BuildForge' },
  { id: 'act-2', timestamp: '2026-03-21T11:30:00Z', type: 'agent', description: 'DeepForge started market analysis session', agent: 'DeepForge' },
  { id: 'act-3', timestamp: '2026-03-21T10:00:00Z', type: 'task', description: 'ScriptForge submitted Episode 1 script for review', agent: 'ScriptForge' },
  { id: 'act-4', timestamp: '2026-03-21T09:30:00Z', type: 'workflow', description: 'Daily Market Data Sync completed successfully' },
  { id: 'act-5', timestamp: '2026-03-21T09:00:00Z', type: 'agent', description: 'EdgePilot updated priority queue for the week', agent: 'EdgePilot' },
  { id: 'act-6', timestamp: '2026-03-21T08:00:00Z', type: 'workflow', description: 'Content Review Pipeline processed 3 items' },
  { id: 'act-7', timestamp: '2026-03-21T07:00:00Z', type: 'system', description: 'Weekly Operations Report generated' },
  { id: 'act-8', timestamp: '2026-03-20T18:00:00Z', type: 'project', description: 'AI Tools project reached 60% completion' },
  { id: 'act-9', timestamp: '2026-03-20T16:00:00Z', type: 'task', description: 'DeepForge completed Prop Firm Comparison Matrix', agent: 'DeepForge' },
  { id: 'act-10', timestamp: '2026-03-20T14:00:00Z', type: 'task', description: 'BuildForge updated Trading Systems Architecture doc', agent: 'BuildForge' },
];

export const systemStatus: SystemStatus = {
  database: 'connected',
  agentWorkers: 'online',
  integrations: 'operational',
  health: 'good',
};

export const focusAreas: FocusArea[] = [
  {
    id: 'fa-1',
    title: 'Trading Systems Development',
    description: 'Building automated trading infrastructure for prop firm evaluations.',
    priority: 'Critical',
    progress: 35,
    relatedProjectId: 'proj-1',
  },
  {
    id: 'fa-2',
    title: 'Content Engine Launch',
    description: 'Launching Trade Truths Unfiltered series and building content pipeline.',
    priority: 'High',
    progress: 45,
    relatedProjectId: 'proj-4',
  },
  {
    id: 'fa-3',
    title: 'Mission Control Dashboard',
    description: 'Central command center for managing all agents and projects.',
    priority: 'Critical',
    progress: 75,
    relatedProjectId: 'proj-3',
  },
  {
    id: 'fa-4',
    title: 'AI Tool Integration',
    description: 'Integrating AI tools across workflows for automation and content.',
    priority: 'Medium',
    progress: 60,
    relatedProjectId: 'proj-2',
  },
];

export const priorityQueue: PriorityItem[] = [
  {
    id: 'pq-1',
    rank: 1,
    title: 'Complete Mission Control Phase 2',
    description: 'Finish Projects, Calendar, and Chief Architect panels.',
    estimatedEffort: '2 days',
    impact: 'High',
  },
  {
    id: 'pq-2',
    rank: 2,
    title: 'Finalize Trading Bot Architecture',
    description: 'Get approval on system design and begin implementation.',
    estimatedEffort: '3 days',
    impact: 'High',
  },
  {
    id: 'pq-3',
    rank: 3,
    title: 'Record Trade Truths Episode 1',
    description: 'Complete script review and record first episode.',
    estimatedEffort: '1 day',
    impact: 'Medium',
  },
  {
    id: 'pq-4',
    rank: 4,
    title: 'Research Prop Firm Rules',
    description: 'Complete analysis of top 5 prop firms for trading.',
    estimatedEffort: '2 days',
    impact: 'High',
  },
  {
    id: 'pq-5',
    rank: 5,
    title: 'Design SaaS Landing Page',
    description: 'Create high-converting landing page for first SaaS MVP.',
    estimatedEffort: '3 days',
    impact: 'Medium',
  },
];

export const decisionQueue: DecisionItem[] = [
  {
    id: 'dq-1',
    title: 'Choose Trading Platform',
    description: 'Select primary trading platform for automated strategies.',
    context: 'Need to decide between TradingView, MetaTrader 5, or custom solution.',
    options: ['TradingView with Pine Script', 'MetaTrader 5 with MQL5', 'Custom Python solution'],
    recommendedOption: 2,
    dueDate: '2026-03-25',
    status: 'pending',
  },
  {
    id: 'dq-2',
    title: 'Content Release Schedule',
    description: 'Decide on weekly content release schedule.',
    context: 'Trade Truths episodes need consistent release timing.',
    options: ['Tuesday 9 AM', 'Thursday 6 PM', 'Saturday 10 AM'],
    recommendedOption: 0,
    dueDate: '2026-03-24',
    status: 'pending',
  },
  {
    id: 'dq-3',
    title: 'SaaS MVP Priority',
    description: 'Determine which SaaS idea to pursue first.',
    context: 'Three ideas validated: trading journal, content scheduler, or analytics dashboard.',
    options: ['Trading Journal', 'Content Scheduler', 'Analytics Dashboard'],
    status: 'pending',
  },
];

export const projects = ['Trading Systems', 'Trading Research', 'Content Engine', 'Automation Systems', 'SaaS MVPs', 'AI Tools'];
export const agentNames = ['Chief Architect', 'EdgePilot', 'DeepForge', 'ScriptForge', 'GrowthForge', 'BuildForge', 'SignalForge', 'Haven'];
